################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=okteto
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=okteto
      - MONGODB_DATABASE=okteto
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'  
  node-red:
    public: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 80:1880
    networks:
      - node-red-net
    volumes:
      - node-red:/home/94r4d0x/.node-red
    links:
      - mongodb


volumes:
  node-red:
    size: 2Gi
  mongodb_data:
    driver: local
    size: 2Gi
  
networks:
  node-red-net:
 

